trigger:
- main
strategy:
  matrix:
    linux: 
      operatingSystem: 'ubuntu-latest'
    macos:
      operatingSystem: 'macos-lates' 

pool:
  vmImage: $(operatingSystem)

steps:
- script: echo Running on $(operratingSystem)
  displayName: 'Run a one-line script'
